name: Flutter Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.4.0' # Versión compatible de Flutter

    - name: Set up Java on Windows
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Configura Java para Windows (requisito de Gradle)
        java-version: '17'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.4.0' # Versión compatible de Flutter

    - name: Set up CocoaPods
      run: sudo gem install cocoapods

    - name: Get dependencies
      run: flutter pub get

    - name: Build iOS
      run: flutter build ios --release

    - name: Upload iOS App as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ios
        path: build/ios/ipa
